### ISSUE TITLE
Global redesign to pixel art

### ISSUE THREAD

**Issue by Chnapy** [Chnapy/timeflies#75]
Global redesign of the app.

Including
- [x] Character new sprites with Pita graphics #66
- [x] Spell new sprites with Frostwindz graphics #70 
- [x] Tile map with Pita tiles #77 
- [x] Font with a pixel art font #78 
- [x] UI global design #30 #31
